feat: complete rabbitmq-watcher
pycasbin/rabbitmq-watcher pull request #1
Opened 2023-07-03 02:44 UTC by BustDot

2023-07-03 03:19 UTC, leeqvip requested changes

2023-07-03 03:19 UTC, leeqvip commented on README.md
> +from rabbitmq_watcher import new_watcher
Please change the package name `rabbitmq_watcher` to `casbin_rabbitmq_watcher`

2023-07-03 03:19 UTC, leeqvip commented on tests/test_rabbit_watcher.py
> +            print("update callback, msg: {}".format(msg))
Please add an assertion in the callback, please ensure that the message is received in the callback().

2023-07-04 05:29 UTC, hsluoyz commented
@leeqvip plz review

2023-07-05 02:47 UTC, leeqvip approved these changes

2023-07-05 02:48 UTC, merged